/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.freaksparty.ficonbar.window;

import FICOnBar.entity.AppUser;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.freaksparty.ficonbar.util.DBSession;
import org.freaksparty.ficonbar.util.User;
import org.freaksparty.ficonbar.util.Util;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Osane
 */
public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
        getRootPane().setDefaultButton(btnLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(41, 44, 47));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(355, 188));
        setPreferredSize(new java.awt.Dimension(500, 250));
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("FIC OnBar");
        getContentPane().add(lblTitle, java.awt.BorderLayout.PAGE_START);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(355, 170));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUser.setText("Usuario");
        jLayeredPane1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, 30));

        txtUser.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUser.setNextFocusableComponent(txtPassword);
        txtUser.setPreferredSize(new java.awt.Dimension(50, 50));
        jLayeredPane1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 160, 30));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Contraseña");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 130, 30));

        btnLogin.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnLogin.setText("Entrar");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setMaximumSize(new java.awt.Dimension(300, 100));
        btnLogin.setPreferredSize(new java.awt.Dimension(120, 37));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 120, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPassword.setNextFocusableComponent(btnLogin);
        jLayeredPane1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 160, 30));
        txtPassword.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
      
       String userName = txtUser.getText();
       String userPassword = new String(txtPassword.getPassword());
       
       MessageDigest digest;
        try {
            //Creamos el hash de la constraseña introducida
            digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(userPassword.getBytes("UTF-8"));
            StringBuffer encryptedPass = new StringBuffer();
            for (int i = 0; i < hash.length; i++) {
                encryptedPass.append(Integer.toString((hash[i] & 0xff) + 0x100, 16).substring(1));
            }
           
            Session session = DBSession.getSession();
            
            //Hacemos la consulta
            Query query = session.createQuery("select u from AppUser u where name = :userName").setParameter("userName", userName);
            List<AppUser> listUsuario = query.list();
            AppUser u = new AppUser();
            
            //Si encontró el usuario... 
            if(!listUsuario.isEmpty()){
                u = listUsuario.get(0);
                //...comprobamos si la contraseña es correcta
                if(encryptedPass.toString().equals(u.getPassword())){
                    User.user = u;
                    Util.registerLogToDB("Inicio de sesion.",u.getUserId());
                    new InitialWindow().setVisible(true);
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(this,"El usuario o la contraseña son incorrectos.","Error", JOptionPane.ERROR_MESSAGE);
            }
            //Si no encontró el usuario mostramos un error.
            else
                JOptionPane.showMessageDialog(this,"El usuario o la contraseña son incorrectos.","Error", JOptionPane.ERROR_MESSAGE);

        } catch (NoSuchAlgorithmException | UnsupportedEncodingException ex) {
            Logger.getLogger(LoginWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
