/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.freaksparty.ficonbar.window;

import FICOnBar.entity.Product;
import FICOnBar.entity.ProductType;
import java.util.List;
import javax.swing.JOptionPane;
import org.freaksparty.ficonbar.util.User;
import org.freaksparty.ficonbar.util.Util;
import org.hibernate.HibernateException;

/**
 *
 * @author Osane
 */
public class ModifyProductWindow extends javax.swing.JDialog {
    private int numProdModified = 0;
    public boolean cancel = false;
    private List<Product> productList = null;
    private boolean combosInitiated = false;
    private Product product = null;

    /**
     * Creates new form ModifyProductWindow
     */
    public ModifyProductWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initCombos();
        combosInitiated = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProdType = new javax.swing.JLabel();
        cmbProdType = new javax.swing.JComboBox<>();
        lblProduct = new javax.swing.JLabel();
        cmbProduct = new javax.swing.JComboBox<>();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblBarcode = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        lblNewType = new javax.swing.JLabel();
        cmbNewType = new javax.swing.JComboBox<>();
        lblComplementOf = new javax.swing.JLabel();
        cmbComplementOf = new javax.swing.JComboBox<>();
        btnAcept = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblProdType.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblProdType.setText("Tipo prod.");

        cmbProdType.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        cmbProdType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProdType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdTypeActionPerformed(evt);
            }
        });

        lblProduct.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblProduct.setText("Producto");

        cmbProduct.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        cmbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblName.setText("Nombre");

        txtName.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtName.setEnabled(false);

        lblBarcode.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblBarcode.setText("Cod. barras");

        txtBarcode.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtBarcode.setEnabled(false);

        lblNewType.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblNewType.setText("Tipo");

        cmbNewType.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        cmbNewType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNewType.setEnabled(false);

        lblComplementOf.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblComplementOf.setText("Compl. de");

        cmbComplementOf.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        cmbComplementOf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbComplementOf.setEnabled(false);

        btnAcept.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnAcept.setText("Aceptar");
        btnAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProduct)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAcept)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblBarcode)
                                    .addComponent(lblNewType)
                                    .addComponent(lblComplementOf, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbComplementOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbNewType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnClose)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                            .addComponent(txtName)))))
                            .addComponent(lblProdType)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbProdType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbProduct, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(53, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProdType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbProdType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBarcode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewType)
                    .addComponent(cmbNewType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplementOf)
                    .addComponent(cmbComplementOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcept)
                    .addComponent(btnClose))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        if(numProdModified == 0)
            cancel = true;
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptActionPerformed
        if(cmbProdType.getSelectedIndex() == 0)
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de producto.","Warning",JOptionPane.WARNING_MESSAGE);
        
        if(cmbProduct.getSelectedIndex() == 0)
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto.","Warning",JOptionPane.WARNING_MESSAGE);
        
        if(!hasChanges(txtName.getText(), txtBarcode.getText(), cmbComplementOf.getSelectedIndex(), cmbNewType.getSelectedIndex()))
            JOptionPane.showMessageDialog(this, "Debe hacer algún cambio.","Warning",JOptionPane.WARNING_MESSAGE);
        try{
            String barcode = txtBarcode.getText() == null ? "" : txtBarcode.getText();
            Util.updatePoductInDB(productList.get(cmbProduct.getSelectedIndex() - 1).getProductId(), txtName.getText(), barcode, cmbNewType.getSelectedIndex(), cmbComplementOf.getSelectedIndex());
            Util.registerLogToDB("Modificado producto ", User.user.getUserId());
            resetData();
        }catch(HibernateException hEx){
            Util.registerLogToDB(hEx.getCause().getMessage(), User.user.getUserId());
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error, contacte a un administrador.","Error",JOptionPane.ERROR_MESSAGE);
            if(numProdModified == 0)
                cancel = true;
            this.dispose();
        }
        numProdModified++;
    }//GEN-LAST:event_btnAceptActionPerformed

    private void cmbProdTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdTypeActionPerformed
        if(cmbProdType.getSelectedIndex() != 0){
            productList = Util.getProductByType(cmbProdType.getSelectedIndex());
            cmbProduct.removeAllItems();
            cmbProduct.addItem("-");            
            for(Product p:productList)
                cmbProduct.addItem(p.getName());
        }
    }//GEN-LAST:event_cmbProdTypeActionPerformed

    private void cmbProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductActionPerformed
        if(cmbProduct.getSelectedIndex() > 0 && combosInitiated && productList.size() > 0){
            product = productList.get(cmbProduct.getSelectedIndex() - 1);
            txtName.setText(product.getName());
            txtName.setEnabled(true);
            txtBarcode.setText(product.getBarcode() == null ? "" : product.getBarcode());
            txtBarcode.setEnabled(true);
            cmbNewType.setSelectedIndex(product.getProductTypeByProductType().getProductTypeId());
            cmbNewType.setEnabled(true);
            cmbComplementOf.setSelectedIndex(product.getProductTypeByComplementOf() == null ? 0 : product.getProductTypeByComplementOf().getProductTypeId());
            cmbComplementOf.setEnabled(true);
        }
    }//GEN-LAST:event_cmbProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifyProductWindow dialog = new ModifyProductWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void initCombos(){
        cmbProdType.removeAllItems();
        cmbNewType.removeAllItems();
        cmbComplementOf.removeAllItems();
        cmbProdType.addItem("-");
        cmbNewType.addItem("-");
        cmbComplementOf.addItem("-");
        List<ProductType> typeList = Util.getProductTypeAll();
        for(ProductType pt:typeList){
            cmbProdType.addItem(pt.getName());
            cmbNewType.addItem(pt.getName());
            cmbComplementOf.addItem(pt.getName());
        }
    }
    
    private void resetData(){
        txtBarcode.setText("");
        txtBarcode.setEnabled(false);
        txtName.setText("");
        txtName.setEnabled(false);
        initCombos();
        cmbComplementOf.setEnabled(false);
        cmbNewType.setEnabled(false); 
    }
    
    private boolean hasChanges(String name, String barcode, int complementOf, int newType){
        return !product.getName().equals(name) || 
                !product.getBarcode().equals(barcode) ||
                (product.getProductTypeByProductType().getProductTypeId() != newType) ||
                (product.getProductTypeByComplementOf().getProductTypeId() != complementOf);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcept;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox<String> cmbComplementOf;
    private javax.swing.JComboBox<String> cmbNewType;
    private javax.swing.JComboBox<String> cmbProdType;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblComplementOf;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewType;
    private javax.swing.JLabel lblProdType;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
