/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.freaksparty.ficonbar.window;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_OPTION;
import org.freaksparty.ficonbar.util.Customer;
import org.freaksparty.ficonbar.util.DynamicComponents;
import org.freaksparty.ficonbar.util.User;
import org.freaksparty.ficonbar.util.Util;

/**
 *
 * @author Osane
 */
public class PaymentWindow extends javax.swing.JDialog {

    public boolean cancel = true;
    
    /**
     * Creates new form PaymentWindow
     */
    public PaymentWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(btnAccept);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtTotalPayed = new javax.swing.JTextField();
        buttonPanel = new java.awt.Panel();
        btnAccept = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1500, 700));
        setMinimumSize(new java.awt.Dimension(100, 101));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(380, 250));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        lblTitle.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Importe abonado");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setMaximumSize(new java.awt.Dimension(600, 43));
        lblTitle.setPreferredSize(new java.awt.Dimension(400, 43));

        txtTotalPayed.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        txtTotalPayed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalPayed.setToolTipText("");
        txtTotalPayed.setMargin(new java.awt.Insets(2, 8, 2, 8));
        txtTotalPayed.setMaximumSize(new java.awt.Dimension(400, 250));
        txtTotalPayed.setMinimumSize(new java.awt.Dimension(6, 1));
        txtTotalPayed.setPreferredSize(new java.awt.Dimension(20, 48));

        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.LINE_AXIS));

        btnAccept.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnAccept.setText("Aceptar");
        btnAccept.setMaximumSize(new java.awt.Dimension(180, 150));
        btnAccept.setPreferredSize(new java.awt.Dimension(70, 30));
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        buttonPanel.add(btnAccept);

        btnCancel.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setActionCommand("");
        btnCancel.setMaximumSize(new java.awt.Dimension(180, 150));
        btnCancel.setPreferredSize(new java.awt.Dimension(70, 30));
        btnCancel.setRequestFocusEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        buttonPanel.add(btnCancel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalPayed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtTotalPayed, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        
        float change = 0, altTotal = 0, payed = 0;
        String textTotal = DynamicComponents.getTxtTotalPrice().getText();
        String textPayed = txtTotalPayed.getText();
        String changeString = "";
        
        if(textPayed.length() > 0)
            payed = Float.parseFloat(textPayed.replace(',', '.'));
        else
            JOptionPane.showMessageDialog(this, "Debe introducir un valor en el campo de texto","Warning",JOptionPane.INFORMATION_MESSAGE);
        
        if(textTotal.length() > 0){
            textTotal = textTotal.substring(textTotal.length() - (textTotal.length() - 8));
            textTotal = textTotal.replace(',', '.');
            altTotal = Float.parseFloat(textTotal);
            if(payed < altTotal){
                JOptionPane.showMessageDialog(this, "El valor introducido debe ser igual o mayor a la cantidad a pagar.","Warning",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            change =  payed - altTotal;
            changeString = String.format("%.2f", change);
        }
       Object[] options = {"OK"};
        int dlg = JOptionPane.showOptionDialog(this, "Cambio: " + changeString + "€","Cambio",JOptionPane.PLAIN_MESSAGE,JOptionPane.INFORMATION_MESSAGE,null,options,options[0]);
        
        if(dlg == OK_OPTION){
            Util.registerLogToDB("El cliente " + Customer.client.getName() + " debe pagar" + altTotal + ", ha entregado " +payed + "€. Su cambio es de " + changeString + "€.", User.user.getUserId());
            cancel = false;
            this.dispose(); 
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cancel = true;
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaymentWindow dialog = new PaymentWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                    
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCancel;
    private java.awt.Panel buttonPanel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtTotalPayed;
    // End of variables declaration//GEN-END:variables
}
