package FICOnBar.entity;
// Generated 08-ene-2016 0:23:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AppLog generated by hbm2java
 */
public class AppLog  implements java.io.Serializable {


     private Integer logId;
     private AppUser appUser;
     private String description;
     private Date dateTime;

    public AppLog() {
    }

    public AppLog(AppUser appUser, String description, Date dateTime) {
       this.appUser = appUser;
       this.description = description;
       this.dateTime = dateTime;
    }
   
    public Integer getLogId() {
        return this.logId;
    }
    
    public void setLogId(Integer logId) {
        this.logId = logId;
    }
    public AppUser getAppUser() {
        return this.appUser;
    }
    
    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


