package FICOnBar.entity;
// Generated 08-ene-2016 0:23:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClientType generated by hbm2java
 */
public class ClientType  implements java.io.Serializable {


     private Integer clientTypeId;
     private String name;
     private Set clients = new HashSet(0);
     private Set prices = new HashSet(0);

    public ClientType() {
    }

	
    public ClientType(String name) {
        this.name = name;
    }
    public ClientType(String name, Set clients, Set prices) {
       this.name = name;
       this.clients = clients;
       this.prices = prices;
    }
   
    public Integer getClientTypeId() {
        return this.clientTypeId;
    }
    
    public void setClientTypeId(Integer clientTypeId) {
        this.clientTypeId = clientTypeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }
    public Set getPrices() {
        return this.prices;
    }
    
    public void setPrices(Set prices) {
        this.prices = prices;
    }




}


