package FICOnBar.entity;
// Generated 08-ene-2016 0:23:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer clientId;
     private ClientType clientType;
     private String name;
     private String barcode;
     private Set sales = new HashSet(0);

    public Client() {
    }

	
    public Client(ClientType clientType, String name) {
        this.clientType = clientType;
        this.name = name;
    }
    public Client(ClientType clientType, String name, String barcode, Set sales) {
       this.clientType = clientType;
       this.name = name;
       this.barcode = barcode;
       this.sales = sales;
    }
   
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }
    public ClientType getClientType() {
        return this.clientType;
    }
    
    public void setClientType(ClientType clientType) {
        this.clientType = clientType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
    public Set getSales() {
        return this.sales;
    }
    
    public void setSales(Set sales) {
        this.sales = sales;
    }




}


