package FICOnBar.entity;
// Generated 08-ene-2016 0:23:29 by Hibernate Tools 4.3.1



/**
 * Price generated by hbm2java
 */
public class Price  implements java.io.Serializable {


     private PriceId id;
     private ClientType clientType;
     private Product product;
     private float amount;

    public Price() {
    }

    public Price(PriceId id, ClientType clientType, Product product, float amount) {
       this.id = id;
       this.clientType = clientType;
       this.product = product;
       this.amount = amount;
    }
   
    public PriceId getId() {
        return this.id;
    }
    
    public void setId(PriceId id) {
        this.id = id;
    }
    public ClientType getClientType() {
        return this.clientType;
    }
    
    public void setClientType(ClientType clientType) {
        this.clientType = clientType;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }




}


