package FICOnBar.entity;
// Generated 08-ene-2016 0:23:29 by Hibernate Tools 4.3.1



/**
 * PriceId generated by hbm2java
 */
public class PriceId  implements java.io.Serializable {


     private int product;
     private int clientType;

    public PriceId() {
    }

    public PriceId(int product, int clientType) {
       this.product = product;
       this.clientType = clientType;
    }
   
    public int getProduct() {
        return this.product;
    }
    
    public void setProduct(int product) {
        this.product = product;
    }
    public int getClientType() {
        return this.clientType;
    }
    
    public void setClientType(int clientType) {
        this.clientType = clientType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PriceId) ) return false;
		 PriceId castOther = ( PriceId ) other; 
         
		 return (this.getProduct()==castOther.getProduct())
 && (this.getClientType()==castOther.getClientType());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProduct();
         result = 37 * result + this.getClientType();
         return result;
   }   


}


