package FICOnBar.entity;
// Generated 08-ene-2016 0:23:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.freaksparty.ficonbar.util.ButtonEntity;

/**
 * ProductType generated by hbm2java
 */
public class ProductType  implements java.io.Serializable, ButtonEntity {


     private Integer productTypeId;
     private String name;
     private Set productsForComplementOf = new HashSet(0);
     private Set productsForProductType = new HashSet(0);

    public ProductType() {
    }

	
    public ProductType(String name) {
        this.name = name;
    }
    public ProductType(String name, Set productsForComplementOf, Set productsForProductType) {
       this.name = name;
       this.productsForComplementOf = productsForComplementOf;
       this.productsForProductType = productsForProductType;
    }
   
    public Integer getProductTypeId() {
        return this.productTypeId;
    }
    
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProductsForComplementOf() {
        return this.productsForComplementOf;
    }
    
    public void setProductsForComplementOf(Set productsForComplementOf) {
        this.productsForComplementOf = productsForComplementOf;
    }
    public Set getProductsForProductType() {
        return this.productsForProductType;
    }
    
    public void setProductsForProductType(Set productsForProductType) {
        this.productsForProductType = productsForProductType;
    }




}


