package FICOnBar.entity;
// Generated 08-ene-2016 0:23:29 by Hibernate Tools 4.3.1



/**
 * SaleId generated by hbm2java
 */
public class SaleId  implements java.io.Serializable {


     private int product;
     private int client;

    public SaleId() {
    }

    public SaleId(int product, int client) {
       this.product = product;
       this.client = client;
    }
   
    public int getProduct() {
        return this.product;
    }
    
    public void setProduct(int product) {
        this.product = product;
    }
    public int getClient() {
        return this.client;
    }
    
    public void setClient(int client) {
        this.client = client;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SaleId) ) return false;
		 SaleId castOther = ( SaleId ) other; 
         
		 return (this.getProduct()==castOther.getProduct())
 && (this.getClient()==castOther.getClient());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProduct();
         result = 37 * result + this.getClient();
         return result;
   }   


}


