package FICOnBar.entity;
// Generated 08-ene-2016 0:23:29 by Hibernate Tools 4.3.1



/**
 * Sale generated by hbm2java
 */
public class Sale  implements java.io.Serializable {


     private SaleId id;
     private Client client;
     private Product product;
     private int amount;
     private float total;

    public Sale() {
    }

    public Sale(SaleId id, Client client, Product product, int amount, float total) {
       this.id = id;
       this.client = client;
       this.product = product;
       this.amount = amount;
       this.total = total;
    }
   
    public SaleId getId() {
        return this.id;
    }
    
    public void setId(SaleId id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }




}


